name: ci

on:
  push:
    branches:
      - $default-branch
      - cicd-setup
  pull_request:
    branches:
      - $default-branch
      - cicd-setup

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: ["3.12", "3.13", "3.14", "3.15"]
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Lint and format
        run: |
          uv add --dev ruff  # Redundant with pyproject.toml
          uv run ruff check --fix
          uv run ruff format

      - name: Security scan of local code
        continue-on-error: true
        run: |
          uv add --dev bandit # Redundant with pyproject.toml
          uv run bandit -r . -c pyproject.toml -f html -o bandit-code-report.htm
          
      - name: Upload bandit code scan artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-code-report-html
          path: bandit-code-report.htm
          
      - name: Security scan of dependencies
        continue-on-error: true
        run: |
          uv run bandit -r . -c bandit_full_scan.toml -f html -o bandit-deps-report.htm
          
      - name: Upload bandit dependency scan artifact
        uses: actions/upload-artifact@v4
        with:
          name: bandit-deps-report-html
          path: bandit-deps-report.htm

      - name: Unit tests and code coverage
        run: | 
          uv run coverage run -m pytest .
          uv run coverage report --format=markdown --show-missing --skip-covered > coverage.md

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-md
          path: coverage.md