name: ci

on:
  push:
    branches:
      - $default-branch
      - cicd-setup
  pull_request:
    branches:
      - $default-branch
      - cicd-setup

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: ["3.12", "3.13", "3.14", "3.15"]
        python-version: ["3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          version: "latest"
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv sync --dev

      - name: Lint and format
        run: |
          uv add --dev ruff  # Redundant with pyproject.toml
          uv run ruff check --fix
          uv run ruff format

#      - name: Type checks
#        run: |
#           uv tool install mypy
#           mypy .

#      - name: Security checks
#        run: |
#          uv tool install bandit
#          bandit -r your_package_name

      - name: Unit tests and code coverage
        run: | 
          uv run coverage run -m pytest .
          uv run coverage report --format=markdown --show-missing --skip-covered > coverage.md

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-md
          path: coverage.md